### PR TITLE
Added right-to-left option to io.TextInput

### PR DESCRIPTION
**Pull request by fladd**
The user can now set `message_right_to_left` as well as `user_right_to_left` to `True`, which will result in both being shown (and updated) in right-to-left.

### CODE REVIEW

**Comment by fladd** [comment]
This is fixing https://github.com/expyriment/expyriment/issues/112

**Comment by lindemann09** [comment]
I can not merge it, because of this commit 9fdbb0069ef0531e35c4b61b31541f969876bd0a (which is on master). Can you merge it?

**Comment by fladd** [comment]
I added the character_filter changes to this branch now. So after review you can merge by accepting the changes of the branch over the ones in master.

**Comment by lindemann09** [comment]
Can you merge it? I can much easier resolve the conflict, I guess?

**Pull request merged**
