### PR TITLE
Tags as version

### PR DESCRIPTION
**Pull request by fladd**
This uses `git describe --tags --dirty --always` as version number. Revision number is thus obsolete.

@lindemann09 Let me know what you think.

### CODE REVIEW

**Comment by lindemann09** [comment]
That might create some problems for the Debian packaging. But we will see that later.

**Comment by fladd** [comment]
Does it? I actually thought that you use `git describe` anyway for the debian package. I thought I saw that kind of version formatting at some point in one of the nightly builds on dropbox.

We don't have to use the tag system, I just thought it would be a nice way to a) have revision and version in one variable, and b) get rid of the versioning relying on some strings in changes.md

**Comment by lindemann09** [comment]
I am not sure. Possibly it is not a problem. As long as git is only required  for building the package, but not for the installation. I can't keep track of the whole procedure.

**Comment by fladd** [comment]
Git is only needed when installing/building from source. Once expyriment is "built", git is not needed anymore, since the information (version number), is then in the header of each individual file (the whole reason for the 'build' process). In that regard, nothing has changed.

**Pull request merged**
