### PR TITLE
colour coding for refreshrate reporting

### PR DESCRIPTION
**Pull request by fladd**
Implementing https://trello.com/c/qTs3zxom/210-test-suite-visual-test

### CODE REVIEW

**Comment by lindemann09** [comment]
Nice,

**Comment by lindemann09** [comment]
Should this be also merged to the Python3 branch? Why only to new_audio_and video?

**Comment by fladd** [comment]
The new_audio_and_video branch will eventually be merged into the Python3 branch, yes.

**Comment by lindemann09** [comment]
OK

On 12.07.2016 17:03, Florian Krause wrote:
>
> The new_audio_and_video branch will eventually be merged into the 
> Python3 branch, yes.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub 
> <https://github.com/expyriment/expyriment/pull/84#issuecomment-232076151>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/ACGc5tv7FnBbsKqIdVgM_qbxIy2tzZYpks5qU6yqgaJpZM4JKdVo>.
>

-- 
Dr. Oliver Lindemann
Division of Cognitive Science - University of Potsdam
http://www.cognitive-psychology.eu/lindemann

**Pull request merged**
