### PR TITLE
add_full_factorial

### PR DESCRIPTION
**Pull request by lindemann09**

### CODE REVIEW

**Comment by fladd** [comment]
I like it, especially for the blocks! I don't understand the benefit for the trials, though. It seems I would still need to loop over everything anyway to put stimuli in there?

**Comment by lindemann09** [comment]
I  never used add stimuli to design.

**Comment by fladd** [comment]
???

**Comment by lindemann09** [comment]
I think usually teach my students not to add stimuli to the design for several reasons. I guess it's basically you that uses this function.  If you think the new method is a problem then do not merge.

**Comment by fladd** [comment]
We might talk about different things here. Adding stimuli to an Experiment to build a complete hierarchy is a core principle of Expyriment. I am not even sure if the logging of stimuli IDs in the event files are meaningful if you don't do that :-)

**Pull request merged**
