### PR TITLE
deprecated -> obsolete

### PR DESCRIPTION
**Pull request by lindemann09**
I changed all deprecated classes, methods to obsolete. That is, they now raise an runtime error. Only one deprecated parameter remains (control.start). See also new stimuli module _obsolete.py What do you think?

### CODE REVIEW

**Comment by fladd** [comment]
I would suggest to first throw dedicated DepricatedWarnings and then remove the deprecated methods, once Expyriment hits 1.0.

**Comment by lindemann09** [comment]
We throw DepricatedWarnings now for more than three years!

**Comment by lindemann09** [comment]
Do you mean with warnings this https://docs.python.org/2/library/exceptions.html#exceptions.Warning
or just a text output! Please take into account that most users under Windows do not notice anything from the console output.

**Comment by lindemann09** [comment]
Like this? https://github.com/expyriment/expyriment/commit/43f52906da321fa0d4d34e58e955820a58b46f18

**Comment by fladd** [comment]
With DeprecationWarning, I mean https://docs.python.org/2/library/exceptions.html#exceptions.DeprecationWarning

Warnings are like Exceptions, but instead of crashing the entire programme, they will only print a warning in the console (and in our case also into the log file), when caught.

**Comment by fladd** [comment]
With DeprecationWarning, I mean https://docs.python.org/2/library/exceptions.html#exceptions.DeprecationWarning

Warnings are like Exceptions, but instead of crashing the entire programme, they will only print a warning in the console (and in our case also into the log file), when caught.

**Comment by lindemann09** [comment]
That is not true. Warnings also quit the program. I do not notice any
differene to an RuntimeError.

Oliver



On 2015-01-28 15:15, Florian Krause wrote:
>
> With DeprecationWarning, I mean
> https://docs.python.org/2/library/exceptions.html#exceptions.DeprecationWarning
>
> Warnings are like Exceptions, but instead of crashing the entire
> programme, they will only print a warning in the console (and in our
> case also into the log file), when caught.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/expyriment/expyriment/pull/53#issuecomment-71840585>.
>

-- 
/*Dr. Oliver Lindemann*
Division of Cognitive Science
University of Potsdam/

Karl - Liebknecht Str. 24/25, Building 14, 14476 Potsdam, Germany
Tel: +49 - 331 - 977 2915, Fax: +49 - 331 - 977 2794
Room: 6.24, Building 14, http://www.cognitive-psychology.eu/lindemann

**Comment by fladd** [comment]
Actually, since Python 2.7 they are even ignored (so not even printed). This is not what we want, so we need to switch this on again:

```
 import warnings
 warnings.simplefilter('always', DeprecationWarning)
 warnings.warn("deprecated", DeprecationWarning)
```

**Comment by lindemann09** [comment]
Ok, that is something else! You want to use the warnings module not the
"raise" method (like `raise DeprecationWarning("blaa bla")`). This
output is difficult to notice, if you do not work with a command line.

Please change it, as you want it.

Oliver



On 2015-01-28 15:54, Florian Krause wrote:
>
> Actually, since Python 2.7 they are even ignored (so not even
> printed). This is not what we want, so we need to switch this on again:
>
> | import warnings
>  warnings.simplefilter('always', DeprecationWarning)
>  warnings.warn("deprecated", DeprecationWarning)
> |
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/expyriment/expyriment/pull/53#issuecomment-71847038>.
>

-- 
/*Dr. Oliver Lindemann*
Division of Cognitive Science
University of Potsdam/

Karl - Liebknecht Str. 24/25, Building 14, 14476 Potsdam, Germany
Tel: +49 - 331 - 977 2915, Fax: +49 - 331 - 977 2794
Room: 6.24, Building 14, http://www.cognitive-psychology.eu/lindemann

**Comment by fladd** [comment]
We can always configure the warning filter to raise an error for the warning, if simple printing and logging in the event file is not sufficient for you. But with this, the message to the user is at least clear, since he/she gets a "DeprecationWarning" and not a "RuntimeError".

**Comment by lindemann09** [comment]
Done. Please merge.

**Pull request merged**
