### PR TITLE
new colour class

### LINKED ISSUE #153: Bug in Colour
https://github.com/expyriment/expyriment/blob/f2cfb025cf9e2221b2fea52353255c093781a849/expyriment/misc/_colour.py#L195

### PR DESCRIPTION
**Pull request by lindemann09**
I made a new colour class. What do you think, Florian? It would fix #153 .

### CODE REVIEW

**Comment by lindemann09** [comment]
One issue to be discussed: 
The Expyriment constances are UK English (e.g. `C_DARKGREY`) but the html names are US English (see colour module). I therefore define at the moment in `constances.py`

```C_DARKGREY = Colour('expyriment_darkgray')```

How shall we deal with it? `expyriment_darkgrey` whould be also inconsistent with HTML name `gray`. Using aliases? Maybe mention this issue in the docu before you merge.

**Comment by fladd** [comment]
I got two errors while trying it out:

```
>>> c.hls
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\flokra\Documents\GitHub\expyriment\expyriment\misc\_colour.py", line 315, in hls
    return multiply255(colorsys.rgb_to_hls(divide255(self._rgb)))
TypeError: rgb_to_hls() missing 2 required positional arguments: 'g' and 'b'
>>> c.hsv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\flokra\Documents\GitHub\expyriment\expyriment\misc\_colour.py", line 297, in hsv
    return multiply255(colorsys.rgb_to_hsv(divide255(self._rgb)))
TypeError: rgb_to_hsv() missing 2 required positional arguments: 'g' and 'b'
```

Concerning the colour names:
* the web colours are spelled wrongly (US), there is nothing we can do about this as they are standard colour names
* I would stick to normal spelling within Expyriment though (that is, our own colour names)
* We could think about renaming our `C_GREY` and `C_DARKGREY` to `EXPYRIMENT_GREY` and `EXPYRIMENT_DARKGREY`
* I would then include those (with the correct spelling gr**e**y!) in `Colour.list_names`

Speaking of `list_names`: It currently does not really "list names", but returns a (ordered) dictionary with names as key and rgb value as value. We might also want to offer an actual list of colour names.

The method `is_colour_name` could be renamed to `is_colour` and could more generally check if any input is a valid colour (checking a name would be part of that). So `misc.Colour.is_colour("#112233")` would also be `True` while `misc.Colour.is_colour((1,2,3,4)) would not.

**Comment by fladd** [comment]
We could actually also not have any of the Expyriment colours in the Colour class as names...then the class would only do official web colour names. Easy to document. And if someone needs the Expyriment colours, they are still in constants.

**Comment by fladd** [comment]
What do you think @lindemann09 ?

**Comment by lindemann09** [comment]
I merged it.

**Pull request merged**
