### PR TITLE
CHANGE: no import of extras

### PR DESCRIPTION
**Pull request by lindemann09**
As I wrote in Trello, Expyriment become too slow in my view. This change makes a huge difference, but the users have now to import extras manually.

### CODE REVIEW

**Comment by fladd** [comment]
On my system the change does not make any time difference.
In both cases (i.e. importing expyriment from the developing branch, and from the import_extras branch), the time to import takes between 2.5 and 3 seconds.

I would hence suggest to try to figure out why the import takes so long and see if we can fix this without not importing parts of the library by default.

**Comment by lindemann09** [comment]
As I said: The difference is is import of numpy and especially the import of matplotlib. That takes very long on old PCs. Are you sure that you installed matplotlib?

**Comment by fladd** [comment]
On my machine numpy and pyplot together are imported in under 300ms. So they make about 10% of the import time of whole Expyriment import time. It seems to me that we should rather try to improve the other 90% (if this is possible, that is).

I am also wondering: how long does it take in total to import Expyriment on this old machine? Given the contribution of the two import above, this should take minutes! I have never seen such long import times before. Is this on a single machine? Maybe something is broken there?

**Comment by lindemann09** [comment]
importing Expyriment without extras take about 3-5 seconds. With extras about 20 seconds more.

**Comment by fladd** [comment]
I am confused. Which extra depends on Matlplotlib?

**Comment by lindemann09** [comment]
As I describe it on Trello: gaborpatch is the problem.

I just measured the time for you again on my modern Linux Office maschine. Unfortunately, the factor is even large as I wrote before.
```
# test_script.py
import time
start = start = time.clock() 
import expyriment
end = time.clock()
print end - start
```
With extras: 3.6 seconds, 
without extras 0.25 seconds. 

That is a factor of 14!! I am really surprised that you didn't notice a difference!

**Comment by fladd** [comment]
Cannot find your comment on Trello about GaborPatch. But yes, it is very weird what is going on. Especially that you can get import times on an EEEPc lower than I can get it on a new quad core MacBookPro!

But in general I think that import times have been around 3 seconds before (at least on my machines). While I think that this can be annoying for us developing, I think for the user this doesn't really matter. When starting an experiment, we have the 10 second wait (for Python to stabilise) anyway, so people have to (and really should!) wait there anyway. And when using Expyriment interactively you also import it once only.
Maybe we can implement a switch (which would mainly be for us then), and keep the default for users as it is?

**Comment by lindemann09** [comment]
I made now an extra version of Expyriment for our lab, because for the 
0.8 version of experiment is simply too slow for us. For one experiment, 
we need the GaborPatch. That is why I can't deinstall matplotlib on all 
machines.

We should write in the documentation, that matplotlib slows down the 
start of experiment tremendously. We might otherwise piss of people how 
think it is a lightweight library. I just find it really pity that 
experiment 0.8 become such an heavy weight library.

Oliver


On 11.05.2015 18:00, Florian Krause wrote:
>
> Cannot find your comment on Trello about GaborPatch. But yes, it is 
> very weird what is going on. Especially that you can get import times 
> on an EEEPc lower than I can get it on a new quad core MacBookPro!
>
> But in general I think that import times have been around 3 seconds 
> before (at least on my machines). While I think that this can be 
> annoying for us developing, I think for the user this doesn't really 
> matter. When starting an experiment, we have the 10 second wait (for 
> Python to stabilise) anyway, so people have to (and really should!) 
> wait there anyway. And when using Expyriment interactively you also 
> import it once only.
> Maybe we can implement a switch (which would mainly be for us then), 
> and keep the default for users as it is?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/expyriment/expyriment/pull/58#issuecomment-100957646>.
>

-- 
/*Dr. Oliver Lindemann*
Division of Cognitive Science
University of Potsdam/

Karl - Liebknecht Str. 24/25, Building 14, 14476 Potsdam, Germany
Tel: +49 - 331 - 977 2915, Fax: +49 - 331 - 977 2794
Room: 6.24, Building 14, http://www.cognitive-psychology.eu/lindemann

**Comment by fladd** [comment]
As I said before, I would rather try to figure out WHY the import takes so long on your machine, instead of neglecting the issue.

Also, please be aware that this is might not be a general problem, as on my machines that particular import slows down Expyriment with a factor of 0.1 only! It would be interesting to see if we can find any other machine with these problems.

How about the following compromise:

In case of `import expyriment`, everything gets recursively imported. Just as it is now.

In case of any specific import, like `from expyriment import io`, only the top-level package io is imported, just as specified. If you need io.extras, import it separately.

This would give us the best of both worlds:
In an interactive session we would import expyriment as a whole, and in a script we would use the sub-packages directly, so we do not have to wait 3 seconds on our eeepcs before an experiment starts.

This would also be totally transparent to the user I think.

What do you think?

**Comment by lindemann09** [comment]
why does it take so long? Sorry, I do not understand the question.

We know: It is the import of matplotlib in Gaborpatch (and a bit the 
import of numpy) that takes so long. What do you want to know more?

Oliver


On 11.05.2015 18:44, Florian Krause wrote:
>
> As I said before, I would rather try to figure out WHY the import 
> takes so long on your machine, instead of neglecting the issue.
>
> Also, please be aware that this is might not be a general problem, as 
> on my machines that particular import slows down Expyriment with a 
> factor of 0.1 only! It would be interesting to see if we can find any 
> other machine with these problems.
>
> How about the following compromise:
>
> In case of |import expyriment|, everything gets recursively imported. 
> Just as it is now.
>
> In case of any specific import, like |from expyriment import io|, only 
> the top-level package io is imported, just as specified. If you need 
> io.extras, import it separately.
>
> This would give us the best of both worlds:
> In an interactive session we would import expyriment as a whole, and 
> in a script we would use the sub-packages directly, so we do not have 
> to wait 3 seconds on our eeepcs before an experiment starts.
>
> This would also be totally transparent to the user I think.
>
> What do you think?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/expyriment/expyriment/pull/58#issuecomment-100975013>.
>

-- 
/*Dr. Oliver Lindemann*
Division of Cognitive Science
University of Potsdam/

Karl - Liebknecht Str. 24/25, Building 14, 14476 Potsdam, Germany
Tel: +49 - 331 - 977 2915, Fax: +49 - 331 - 977 2794
Room: 6.24, Building 14, http://www.cognitive-psychology.eu/lindemann

**Comment by fladd** [comment]
I want to understand

A. Why does matplotlib need so long on your machine?

B. Why does expyriment - matplotlib take so long on my machine?

C. Why does matplotlib needs almost no time on my machine?

D. Why does expyriment - matplotlib needs almost no time on your machine?

E. Could there be a python installation problem on your machine? 

F. Could there be a python installation problem on my machine? 

In general I just want to understand what is going on. 


If the behaviour you describe was consistent on all machines then your points are of course valid. The situation just seems a bit more complex to me and I just wanna figure out what's going on. 

Did you also see the second part of my last message?

**Comment by lindemann09** [comment]
I have no idea.
I speculate that RAM is the crucial feature here. I guess that pyplot 
requires a lot of memory, because the import becomes slower on machines 
with less RAM (1GB) and Windows. If you import pylot on old Windows 
PCs,  you hear a lot of hard-disk operations (swapping).

Alternatively, pyplot imports might be slower on Windows than on Linux. 
It feels as if Windows rebuilds some .pyc-files. Under Linux is just 
takes that long if you import it the first time. No idea, just speculation.


Oliver

On 11.05.2015 19:28, Florian Krause wrote:
>
> I want to understand
>
> A. Why does matplotlib need so long on your machine?
>
> B. Why does expyriment - matplotlib take so long on my machine?
>
> C. Why does matplotlib needs almost no time on my machine?
>
> D. Why does expyriment - matplotlib needs almost no time on your machine?
>
> E. Could there be a python installation problem on your machine?
>
> F. Could there be a python installation problem on my machine?
>
> In general I just want to understand what is going on.
>
> If the behaviour you describe was consistent on all machines then your 
> points are of course valid. The situation just seems a bit more 
> complex to me and I just wanna figure out what's going on.
>
> Did you also see the second part of my last message?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/expyriment/expyriment/pull/58#issuecomment-100985841>.
>

-- 
/*Dr. Oliver Lindemann*
Division of Cognitive Science
University of Potsdam/

Karl - Liebknecht Str. 24/25, Building 14, 14476 Potsdam, Germany
Tel: +49 - 331 - 977 2915, Fax: +49 - 331 - 977 2794
Room: 6.24, Building 14, http://www.cognitive-psychology.eu/lindemann

**Comment by lindemann09** [comment]
Regarding you proposal to distinguish between ``import expyriment`` and ``from expyriment import io``. 

That was exactly also my first idea, but I think that is technically not possible in Python, right?

**Comment by fladd** [comment]
You are right. Some things are really annoying in Python. The whole import mechanism is one of those things.

One last suggestion:
We could move the actual imports of the additional packages (e.g. matplotlib) into the init method of the stimulus class itself. Right now, you do a check for the presence of matplotlib there anyway, and throw an exception if it is not there. So, in principle, we could also do the whole import at this point.
This would solve the problem you have right now while still importing the extras automatically.
I am right now not sure if there are other downsides, though.

If this is not possible, or not feasible for some reason, we will do what you suggested.

In relation to this, but irrespective of how we decide: Would you offer detailed descriptions in the installation guide on how to obtain the extra dependencies for all the extras we currently have (at the moment these are matplotlib, pillow and pyxid), or would you rather just mention that extras might have extra dependencies and that those (and installation instructions) can be found in the documentation of that extra?

**Comment by lindemann09** [comment]
OK, we can do move it in the init_method of the class. I have no problem 
with that. That would solves the timing issue for now, but it does not 
address the core of more fundamental problem, which I see with the 
current design of Expyriment.

Just to repeat my argument:
I think that moving imports to __init__ is in the long run very 
inefficient, because you have to do that for every new plug-in. We would 
force people (and us) to program very "unpythonic" just, because we 
think that it is too much to ask from the user to call "import 
expyriment.stimulus.extras" in some rare cases? Note, at the moment 
there are only a few nerds that us the extras.

What I wanted to propose is to see extras not as part of the Exypriment 
core anymore. They are extras! Extras are merely shipped with 
Expyriment, but the are not part of it. Independent from the timing 
issue, I personally even think that it is an advantage to force people 
to import extras manually, because they  become this way aware that they 
use "third-party" or beta features.

The fundamental problem for the future will be that extras are (hopeful) 
rapidly growing......I have for instance a relative fancy dot pattern 
class in the pipeline (that requires image packages and scipy for the 
statistics of the dot distributions)  I would like to include it in the 
future, but I have to say that Expyriment becomes this way heavier and 
heavier. Honestly, I would then personally prefer not to include it, if 
it would be imported for every simple experiment. Such an unnecessary 
overhead...

Oliver


12.05.2015 14:19, Florian Krause wrote:
>
> You are right. Some things are really annoying in Python. The whole 
> import mechanism is one of those things.
>
> One last suggestion:
> We could move the actual imports of the additional packages (e.g. 
> matplotlib) into the init method of the stimulus class itself. Right 
> now, you do a check for the presence of matplotlib there anyway, and 
> throw an exception if it is not there. So, in principle, we could also 
> do the whole import at this point.
> This would solve the problem you have right now while still importing 
> the extras automatically.
> I am right now not sure if there are other downsides, though.
>
> If this is not possible, or not feasible for some reason, we will do 
> what you suggested.
>
> In relation to this, but irrespective of how we decide: Would you 
> offer detailed descriptions in the installation guide on how to obtain 
> the extra dependencies for all the extras we currently have (at the 
> moment these are matplotlib, pillow and pyxid), or would you rather 
> just mention that extras might have extra dependencies and that those 
> (and installation instructions) can be found in the documentation of 
> that extra?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/expyriment/expyriment/pull/58#issuecomment-101256396>.
>

-- 
/*Dr. Oliver Lindemann*
Division of Cognitive Science
University of Potsdam/

Karl - Liebknecht Str. 24/25, Building 14, 14476 Potsdam, Germany
Tel: +49 - 331 - 977 2915, Fax: +49 - 331 - 977 2794
Room: 6.24, Building 14, http://www.cognitive-psychology.eu/lindemann

**Comment by fladd** [comment]
Okay, then let's do it like you suggest.

Just to be clear again, we only do not import the extras then, right?
Any other sub package (e.g. stimuli, io) will still be automatically imported?
If so, we need to somehow document this properly, as this is neither of the two usually used ways to handle imports of large packages in Python and a bit inconsistent.
Could you add this to the documentation?

I will then consequently also not include the extra dependencies in the installation instructions (which I am working on right now).

**Comment by lindemann09** [comment]
Yes of course, only the extras. The API docu of extras look like this 
(https://github.com/expyriment/expyriment/blob/import_extras/expyriment/design/extras/__init__.py 
).  Isn't that enough? (plus release notes, of course)

Actually, the update to 0.8 involves several crucial changes:
Please have a look at the 'changes' that are marked with ATTENTION in 
the change.log 
(https://github.com/expyriment/expyriment/blob/import_extras/CHANGES.md ).

I think, the release notes need to summarizes all these points. Maybe we 
could make an extras website for these crucial changes between 0.7 and 
0.8, because they are really important!

If it is OK, please merge.

Oliver


On 12.05.2015 16:53, Florian Krause wrote:
>
> Okay, then let's do it like you suggest.
>
> Just to be clear again, we only do not import the extras then, right?
> Any other sub package (e.g. stimuli, io) will still be automatically 
> imported?
> If so, we need to somehow document this properly, as this is neither 
> of the two usually used ways to handle imports of large packages in 
> Python and a bit inconsistent.
> Could you add this to the documentation?
>
> I will then consequently also not include the extra dependencies in 
> the installation instructions (which I am working on right now).
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/expyriment/expyriment/pull/58#issuecomment-101307786>.
>

-- 
/*Dr. Oliver Lindemann*
Division of Cognitive Science
University of Potsdam/

Karl - Liebknecht Str. 24/25, Building 14, 14476 Potsdam, Germany
Tel: +49 - 331 - 977 2915, Fax: +49 - 331 - 977 2794
Room: 6.24, Building 14, http://www.cognitive-psychology.eu/lindemann

**Comment by fladd** [comment]
I am not sure if this documentation is enough. Maybe they are.

I am just afraid that a user expects (at least as experienced Python user):

(a) all sub packges are imported (like we did before, and like pygame does)

or

(b) no sub packages are imported (like most python libraries do)

While we will now have:

(c) Some sub packages are imported, while others are not

I think we somehow need to make the user understand why this inconsistency exists.
But it could of course also be that users aren't that confused about it as I think they will be. I am not sure.

Something I was also wondering while looking at the docs: Shouldn't we advertise importing specific extras directly (e.g. `from expyriment.stimuli.extras import DotCloud`) rather than importing the whole extras package (which will partly create the same issues we are currently trying to solve)?

**Comment by lindemann09** [comment]
But, sorry, that is not true, what you are saying. Which packages 
imports everything? Numpy, no. OpenGl, no (it altually imports nothing). 
Also Pygame imports not everything. I remember that e.g pygame. gfxdraw 
has to be imported manually. Why do you thing that Python use would 
expect that?

I scanned three package (Pygame, numpy, pyopengl) documentations and did 
not find anything which tells me, which sub-packages are important and 
which are not.  Strange, right? It seem to be try and error... That is 
of course not good and we can make that better.

Expyriment is in that respect very clear and easier. It imports 
everything except extras submodule. Can it be easier?

Oliver



On 13.05.2015 12:33, Florian Krause wrote:
>
> I am not sure if this documentation is enough. Maybe they are.
>
> I am just afraid that a user expects (at least as experienced Python 
> user):
>
> (a) all sub packges are imported (like we did before, and like pygame 
> does)
>
> or
>
> (b) no sub packages are imported (like most python libraries do)
>
> While we will now have:
>
> (c) Some sub packages are imported, while others are not
>
> I think we somehow need to make the user understand why this 
> inconsistency exists.
> But it could of course also be that users aren't that confused about 
> it as I think they will be. I am not sure.
>
> Something I was also wondering while looking at the docs: Shouldn't we 
> advertise importing specific extras directly (e.g. |from 
> expyriment.stimuli.extras import DotCloud|) rather than importing the 
> whole extras package (which will partly create the same issues we are 
> currently trying to solve)?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/expyriment/expyriment/pull/58#issuecomment-101617794>.
>

-- 
/*Dr. Oliver Lindemann*
Division of Cognitive Science
University of Potsdam/

Karl - Liebknecht Str. 24/25, Building 14, 14476 Potsdam, Germany
Tel: +49 - 331 - 977 2915, Fax: +49 - 331 - 977 2794
Room: 6.24, Building 14, http://www.cognitive-psychology.eu/lindemann

**Comment by fladd** [comment]
Not true? Don't pretty much all packages from Python's standard library import everything?

I actually didn't know that Pygame.gfxdraw is not imported. Thanks for pointing that out. This is a good example why inconsistency is confusing I guess, since I just expected Pygame to import everything (because most things I remember were imported).

And yes, we can do better, I agree.

Let's just do it like this and see what happens.

**Comment by lindemann09** [comment]
Which Python standard library has a sub-packages that is automatically 
imported?  OK, os implies also os.path. But that is the one case, right? 
I think all other standard library packages are flat with no hierarchy.

Standard lib is anyway crude comparison, in my view.  You  can not 
compare it with large libraries like pygame, numpy or experiment. This 
are basic libraries with no further dependencies! Moreover, in 
comparison, the standard library packages are usually very small with 
often not more then 20 functions (and no subpackage).


Best,
Oliver



On 13.05.2015 14:09, Florian Krause wrote:
>
> Not true? Don't pretty much all packages from Python's standard 
> library import everything?
>
> I actually didn't know that Pygame.gfxdraw is not imported. Thanks for 
> pointing that out. This is a good example why inconsistency is 
> confusing I guess, since I just expected Pygame to import everything 
> (because most things I remember were imported).
>
> And yes, we can do better, I agree.
>
> Let's just do it like this and see what happens.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/expyriment/expyriment/pull/58#issuecomment-101643252>.
>

-- 
/*Dr. Oliver Lindemann*
Division of Cognitive Science
University of Potsdam/

Karl - Liebknecht Str. 24/25, Building 14, 14476 Potsdam, Germany
Tel: +49 - 331 - 977 2915, Fax: +49 - 331 - 977 2794
Room: 6.24, Building 14, http://www.cognitive-psychology.eu/lindemann

**Pull request merged**
